# Generated by Django 5.0.14 on 2026-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_sync_unmanaged_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBreederInquiry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('priority', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'breeders_breederinquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalBreederReview',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('stock_health_rating', models.IntegerField(blank=True, null=True)),
                ('communication_rating', models.IntegerField(blank=True, null=True)),
                ('accuracy_rating', models.IntegerField(blank=True, null=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breeders_breederreview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalConsultantBooking',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('requester_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('booking_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('consultant_status', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('response_time_hours', models.FloatField(blank=True, null=True)),
                ('was_fast_response', models.BooleanField(default=False)),
                ('was_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultant_consultantbooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalConversation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('participant_1_id', models.UUIDField()),
                ('participant_2_id', models.UUIDField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messaging_conversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'messaging_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalPaymentFailureLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('payment_intent_id', models.UUIDField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=128, null=True)),
                ('stripe_error', models.JSONField(blank=True, default=dict, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_paymentfailurelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalRefund',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('payment_intent_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_refund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalTrustScoreSnapshot',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('trust_score', models.IntegerField(default=0)),
                ('regulatory_tier', models.CharField(blank=True, max_length=32)),
                ('total_badge_points', models.IntegerField(default=0)),
                ('total_incident_penalties', models.IntegerField(default=0)),
                ('contributing_factors', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_version', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'badges_trustscoresnapshot',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='admininvite',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admininvite',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_sent', 'Email sent'), ('email_failed', 'Email failed'), ('link_available', 'Link available')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='admininvite',
            name='last_delivery_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiflaggedissue',
            name='source_type',
            field=models.CharField(choices=[('incident', 'Incident'), ('consultant_warning', 'Consultant Warning'), ('message_risk', 'Message Risk'), ('breeder_inquiry_risk', 'Breeder Inquiry Risk'), ('booking_risk', 'Booking Risk'), ('payment_risk', 'Payment Risk'), ('trust_drop', 'Trust Drop')], max_length=32),
        ),
    ]
