# Generated by Django 5.0.14 on 2026-04-27 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_externalbreederinquiry_externalbreederreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiflaggedissue',
            name='source_type',
            field=models.CharField(choices=[('incident', 'Incident'), ('consultant_warning', 'Consultant Warning'), ('message_risk', 'Message Risk'), ('breeder_inquiry_risk', 'Breeder Inquiry Risk'), ('booking_risk', 'Booking Risk'), ('payment_risk', 'Payment Risk'), ('trust_drop', 'Trust Drop'), ('support_inquiry', 'Support Inquiry')], max_length=32),
        ),
        migrations.CreateModel(
            name='OperationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.CharField(blank=True, max_length=255)),
                ('slack_bot_token', models.CharField(blank=True, max_length=255)),
                ('slack_channel', models.CharField(blank=True, max_length=255)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=255)),
                ('imap_folder', models.CharField(blank=True, default='INBOX', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operational settings',
                'verbose_name_plural': 'Operational settings',
            },
        ),
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('actioned', 'Actioned'), ('replied', 'Replied'), ('archived', 'Archived'), ('error', 'Error')], default='new', max_length=20)),
                ('matched_entity_type', models.CharField(blank=True, max_length=32)),
                ('matched_entity_id', models.CharField(blank=True, max_length=64)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_rationale', models.TextField(blank=True)),
                ('ai_recommended_actions', models.JSONField(blank=True, default=list)),
                ('ai_raw', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=80)),
                ('ai_error', models.TextField(blank=True)),
                ('response_draft', models.TextField(blank=True)),
                ('response_history', models.JSONField(blank=True, default=list)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='admin_porta_inquiry_status_idx')],
            },
        ),
    ]
