# Generated by Django 5.0.14 on 2026-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_alter_aiflaggedissue_source_type_operationalsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('developer', 'Developer'), ('guest', 'Guest')], default='guest', help_text='guest = read-only access. admin = moderation and operational control. developer = read + write (updates notify super-admins). super_admin = full control (set automatically for Steven/Ben).', max_length=20),
        ),
    ]
