# Generated by Django 5.2.4 on 2026-06-02 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_alter_admininvite_role_alter_adminuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBreederReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_code', models.CharField(max_length=40)),
                ('delivery_method', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('payment_status', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('no_show_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('courier_name', models.CharField(blank=True, max_length=120)),
                ('delivery_zone', models.CharField(blank=True, max_length=20)),
                ('checkout_group_code', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_breederreservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalBreederShippingProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supports_collection', models.BooleanField(default=True)),
                ('supports_delivery', models.BooleanField(default=False)),
                ('collection_radius_km', models.IntegerField(default=0)),
                ('local_zone_km', models.IntegerField(default=0)),
                ('regional_zone_km', models.IntegerField(default=0)),
                ('appointment_only', models.BooleanField(default=False)),
                ('holiday_mode_enabled', models.BooleanField(default=False)),
                ('holiday_message', models.TextField(blank=True)),
                ('collection_address', models.TextField(blank=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_breedershippingprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalBreederVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('licence_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_breederverification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalFeatureDAuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('badge_type', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('action_reason', models.TextField(blank=True)),
                ('previous_state', models.JSONField(blank=True, default=dict, null=True)),
                ('new_state', models.JSONField(blank=True, default=dict, null=True)),
                ('evidence_data', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(blank=True, max_length=255)),
                ('triggered_by_type', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'badges_badgeauditlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMarketplaceSellerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('stripe_connect_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_connect_status', models.CharField(blank=True, max_length=32)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('delivery_sales_enabled', models.BooleanField(default=False)),
                ('delivery_suspended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_sellerprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalReservationDispute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('breeder_response', models.TextField(blank=True)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('resolution_summary', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('breeder_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketplace_reservationdispute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DSARDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artefact_type', models.CharField(choices=[('access_export_json', 'Access export JSON'), ('access_export_html', 'Access export HTML'), ('deletion_report_json', 'Deletion report JSON'), ('deletion_report_html', 'Deletion report HTML')], max_length=32)),
                ('storage_ref', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DSAREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DSARRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('portability', 'Portability'), ('rectification', 'Rectification'), ('erasure', 'Erasure'), ('restriction', 'Restriction'), ('objection', 'Objection')], default='access', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('in_progress', 'In progress'), ('awaiting_dpo_approval', 'Awaiting DPO approval'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('extended', 'Extended'), ('withdrawn', 'Withdrawn'), ('unmatched', 'Unmatched')], default='received', max_length=32)),
                ('subject_user_id', models.UUIDField(blank=True, null=True)),
                ('submitted_email', models.EmailField(max_length=254)),
                ('submitted_name', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('web_form', 'Web form'), ('email', 'Email'), ('in_app', 'In app')], default='email', max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dpo_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('extended', models.BooleanField(default=False)),
                ('extension_reason', models.TextField(blank=True)),
                ('verification_token_hash', models.CharField(blank=True, max_length=128)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_email', models.EmailField(blank=True, max_length=254)),
                ('export_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['received_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='gmail_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='gmail_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='gmail_refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='gmail_sender',
            field=models.CharField(blank=True, default='support@aquaai.uk', max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='privacy_alias_email',
            field=models.CharField(blank=True, default='privacy@aquaai.uk', max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='providers_alias_email',
            field=models.CharField(blank=True, default='providers@aquaai.uk', max_length=255),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='support_alias_email',
            field=models.CharField(blank=True, default='support@aquaai.uk', max_length=255),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='gmail_label_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='gmail_thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='mailbox_kind',
            field=models.CharField(choices=[('general', 'General Support'), ('privacy', 'Privacy'), ('providers', 'Providers')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='to_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='supportinquiry',
            index=models.Index(fields=['mailbox_kind', '-received_at'], name='admp_inquiry_mailbox_idx'),
        ),
        migrations.AddField(
            model_name='dsarevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dsarrequest',
            name='dpo_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dsarrequest',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_requests', to='admin_portal.supportinquiry'),
        ),
        migrations.AddField(
            model_name='dsarevent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admin_portal.dsarrequest'),
        ),
        migrations.AddField(
            model_name='dsardeliverable',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='admin_portal.dsarrequest'),
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['status', 'due_at'], name='admp_dsar_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['submitted_email'], name='admin_porta_dsar_email_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarevent',
            index=models.Index(fields=['request', 'created_at'], name='admin_porta_dsar_event_idx'),
        ),
    ]
