# Generated by Django 5.2.4 on 2026-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_externalbreederreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsettings',
            name='auto_activate_new_accounts',
            field=models.BooleanField(default=False, help_text='When enabled, new breeder and consultant accounts are automatically approved without AI review as soon as the review processor picks them up.'),
        ),
    ]
