# Generated by Django 5.2.14 on 2026-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0009_operationalsettings_auto_activate_new_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsarrequest",
            name="verification_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
