# Generated by Django 5.2.14 on 2026-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0010_dsarrequest_verification_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsarrequest",
            name="login_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsarrequest",
            name="login_confirmed_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
