# Generated by Django 5.2.14 on 2026-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0011_dsarrequest_login_confirmed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="dsarrequest",
            name="login_baseline_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
