# Generated by Django 5.2.14 on 2026-06-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0012_platformsession_dsarrequest_login_baseline_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalsettings",
            name="dsar_auto_send",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, an access/portability data request is compiled and emailed to the requester automatically as soon as their aquaai.uk login is confirmed. Turn off to require an admin to press Approve and send.",
            ),
        ),
        migrations.AlterField(
            model_name="dsardeliverable",
            name="artefact_type",
            field=models.CharField(
                choices=[
                    ("access_export_pdf", "Access export PDF"),
                    ("access_export_json", "Access export JSON"),
                    ("access_export_html", "Access export HTML"),
                    ("deletion_report_json", "Deletion report JSON"),
                    ("deletion_report_html", "Deletion report HTML"),
                ],
                max_length=32,
            ),
        ),
    ]
