# Generated by Django 5.0.14 on 2026-07-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0014_operationalsettings_auto_activate_stagger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalOutstandingToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("jti", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "token_blacklist_outstandingtoken",
                "managed": False,
            },
        ),
    ]
